[versions]
coroutines = "1.5.2"
kotest = "4.6.3"
ktor = "1.6.5"
mokoki = "0.1.0-alpha.6"
okHttp = "4.9.2"
okio = "3.0.0"
retrofit = "2.9.0"
retrofitKotlinConverter = "0.8.0"
runBlocking = "0.1.0-beta.1"
serialization = "1.3.0"

[libraries]
jakewharton-retrofit-retrofit2KotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinConverter" }
javiersc-mokoki-mokokiCore = { module = "com.javiersc.mokoki:mokoki-core", version.ref = "mokoki" }
javiersc-mokoki-mokokiSerialization = { module = "com.javiersc.mokoki:mokoki-serialization", version.ref = "mokoki" }
javiersc-runBlocking-runBlockingCore = { module = "com.javiersc.run-blocking:run-blocking-core", version.ref = "runBlocking" }
javiersc-runBlocking-suspendTest = { module = "com.javiersc.run-blocking:suspend-test", version.ref = "runBlocking" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
ktor-ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ktorClientMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-ktorClientSerialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
squareup-okio-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
