[versions]
android = "7.0.4"
javierscGradlePlugins = "0.1.0-rc.22"
kotlin = "1.6.0"
kotlinBinaryValidator = "0.8.0"

[libraries]
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
javiersc-gradlePlugins-allPluginsX = { module = "com.javiersc.gradle-plugins:all-plugins", version.ref = "javierscGradlePlugins" }
jetbrains-kotlin-kotlinGradlePluginX = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlin-kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
